development:
  adapter: postgresql
  encoding: utf8
  database: angular_rails
  username: postgres
  password: password

  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: angular_rails_test
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: angular_rails_production
  username: postgres
  password: password
